// UI wiring smoke test with explicit DOM/audio/worker stand-ins.
// This is not browser automation, layout validation, or a hardware-audio test.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8'),elements=new Map(),handlers={};
const messages=[],audioMessages=[],downloads=[],storage=new Map(),scheduled=new Map();let timer=0,frameCallback,lastWorker,workletOptions,captureRequests=0;
const drawing=new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),createRadialGradient:()=>({addColorStop(){}})},{get:(obj,key)=>obj[key]||(()=>{})});
class Element{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.children=[];this.attrs={...attrs};this.dataset={};this.value=attrs.value||'';this.min=attrs.min||'';this.max=attrs.max||'';this.type=attrs.type||'';this.id=attrs.id;this.textContent='';this.open=false;this.files=[];this.style={setProperty(){}};const set=new Set();this.classList={add:(v)=>set.add(v),remove:(v)=>set.delete(v),toggle:(v,on)=>{if(on??!set.has(v))set.add(v);else set.delete(v);},contains:v=>set.has(v)};}
 appendChild(child){this.children.push(child);return child;}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k];}addEventListener(type,fn){this['listener_'+type]=fn;}remove(){}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,right:800,bottom:500,width:800,height:500};}getContext(){return drawing;}showModal(){this.open=true;}close(){this.open=false;}focus(){document.activeElement=this;}matches(query){return query.split(',').map(s=>s.trim().toUpperCase()).includes(this.tagName);}click(){if(this.tagName==='A')downloads.push(this);this.onclick?.({detail:1,target:this});}
}
for(const match of html.matchAll(/<([a-z][a-z0-9]*)\b([^>]*\bid="([^"]+)"[^>]*)>/gi)){const attrs=Object.fromEntries([...match[2].matchAll(/([a-zA-Z-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));elements.set(match[3],new Element(match[1],attrs));}
const body=new Element('body');
globalThis.document={body,hidden:false,getElementById:id=>elements.get(id)||null,createElement:tag=>new Element(tag),querySelectorAll:query=>[...elements.values()].filter(e=>query==='dialog'&&e.tagName==='DIALOG'),querySelector:query=>query==='dialog[open]'?[...elements.values()].find(e=>e.tagName==='DIALOG'&&e.open):null,addEventListener:(type,fn)=>{handlers[type]=fn;}};
globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
globalThis.ResizeObserver=class{constructor(fn){this.fn=fn;}observe(){this.fn();}};globalThis.requestAnimationFrame=fn=>{frameCallback=fn;return 1;};
globalThis.setInterval=(fn)=>{scheduled.set(++timer,fn);return timer;};globalThis.setTimeout=(fn)=>{scheduled.set(++timer,fn);return timer;};globalThis.clearTimeout=id=>scheduled.delete(id);
globalThis.Worker=class{constructor(){lastWorker=this;queueMicrotask(()=>this.onmessage?.({data:{type:'ready'}}));}postMessage(m){messages.push(m);}terminate(){}};
class Context{constructor(){this.state='suspended';this.sampleRate=48000;this.baseLatency=.01;this.destination={};this.audioWorklet={addModule:async()=>{}};}async resume(){this.state='running';this.onstatechange?.();}async suspend(){this.state='suspended';this.onstatechange?.();}async close(){this.state='closed';this.onstatechange?.();}createMediaStreamSource(){return {connect(){},disconnect(){}};}createAnalyser(){return {connect(){},getFloatTimeDomainData(a){a.fill(0);}};}}
globalThis.window={AudioContext:Context,devicePixelRatio:1,addEventListener:(type,fn)=>{handlers['window_'+type]=fn;}};
globalThis.AudioWorkletNode=class{constructor(ctx,name,options){workletOptions=options;this.port={postMessage:m=>{audioMessages.push(m);if(m.type==='stopRecord')queueMicrotask(()=>{this.port.onmessage({data:{type:'recordChunk',samples:new Float32Array(1280).fill(.1)}});this.port.onmessage({data:{type:'recordEnd'}});});}};}connect(){}disconnect(){}};
const port={id:'port1',state:'connected',name:'Test controller',onmidimessage:null},access={inputs:new Map([['port1',port]])};
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{requestMIDIAccess:async()=>access,mediaDevices:{getUserMedia:async()=>{captureRequests++;throw new Error('Capture removed');}}}});
const $=id=>elements.get(id),results=[];
async function flush(){for(let i=0;i<5;i++)await new Promise(resolve=>setImmediate(resolve));}
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);}}
function key(type,code){handlers[type]({code,repeat:false,target:body,preventDefault(){}});}
await check('Application initializes every control and its eight-scene palette',async()=>{await import('../dist/app.mjs');await flush();assert.ok($('preset').children.length>=8);assert.equal($('keyboard').children.length,13);assert.ok(messages.some(m=>m.type==='params'));assert.match($('echoOut').textContent,/%/);});
await check('Enable audio and keyboard note on/off reach both engines',async()=>{await $('audioBtn').onclick();key('keydown','KeyA');await flush();const on=messages.findLast(m=>m.type==='noteOn');assert.ok(on);assert.ok(audioMessages.some(m=>m.type==='noteOn'&&m.id===on.id));key('keyup','KeyA');assert.ok(audioMessages.some(m=>m.type==='noteOff'&&m.id===on.id));});
await check('Sustain button holds a keyboard voice until released',async()=>{$('sustainBtn').onclick();key('keydown','KeyS');await flush();const on=messages.findLast(m=>m.type==='noteOn');key('keyup','KeyS');assert.ok(!messages.some(m=>m.type==='noteOff'&&m.id===on.id));$('sustainBtn').onclick();assert.ok(messages.some(m=>m.type==='noteOff'&&m.id===on.id));});
await check('Preset selection and named save persist a sound safely',async()=>{$('preset').value='bells';$('preset').onchange();assert.equal($('tempo').value,120);$('savePatchBtn').onclick();$('patchName').value='My <current>'; $('patchForm').onsubmit({preventDefault(){}});assert.ok(storage.get('rheo.v1.patches').includes('My <current>'));assert.equal($('patchDialog').open,false);assert.ok($('preset').children.some(x=>x.textContent.includes('My <current>')));});
await check('Export creates a downloadable patch without remote calls',async()=>{$('exportPatchBtn').onclick();assert.ok(downloads.some(a=>a.download.endsWith('.json')));});
await check('Malformed patch import reports an error without applying it',async()=>{const old=$('tempo').value;$('patchFile').files=[{size:10,text:async()=>'{bad json'}];await $('patchFile').onchange();assert.match($('message').textContent,/Import failed/);assert.equal($('tempo').value,old);});
await check('Recording produces an audition player and persistent download link',async()=>{$('recordBtn').onclick();$('recordBtn').onclick();await flush();assert.equal($('takesPanel').hidden,false);const row=$('takesList').children[0];assert.ok(row.children.some(x=>x.tagName==='AUDIO'));assert.ok(row.children.some(x=>x.download?.endsWith('.wav')));});
await check('MIDI connection, channel input and disconnect reach the engine',async()=>{await $('midiBtn').onclick();assert.equal(typeof port.onmidimessage,'function');port.onmidimessage({data:[0x91,64,100]});await flush();assert.ok(audioMessages.some(m=>m.type==='noteOn'&&m.group==='midi:port1:1'));port.onmidimessage({data:[0x81,64,0]});await $('midiBtn').onclick();assert.equal(port.onmidimessage,null);});
await check('Synth has no input controls and never requests microphone access',async()=>{assert.equal($('inputBtn'),undefined);assert.equal($('recordSource'),undefined);assert.equal(captureRequests,0);assert.equal(workletOptions.numberOfInputs,0);});
await check('Physical probe controls reach the solver and update their explanation',async()=>{$('pickup').value='2';$('pickup').oninput();$('probeMotion').value='0';$('probeMotion').oninput();$('buoyancy').value='1.2';$('buoyancy').oninput();const last=messages.findLast(m=>m.type==='params');assert.equal(last.params.pickup,2);assert.equal(last.params.probeMotion,0);assert.equal(last.params.buoyancy,1.2);assert.match($('pickupDescription').textContent,/Pressure/);assert.equal($('motionLabel').textContent,'EULERIAN');});
await check('Thermal experiment configures listening-only and supplies its initial condition',async()=>{$('plumeExperiment').onclick();assert.ok(messages.some(m=>m.type==='experiment'&&m.kind==='plume'));const last=messages.findLast(m=>m.type==='params');assert.equal(last.params.excite,0);assert.equal(last.params.flow,1);assert.equal(last.params.buoyancy,1.5);assert.match($('experimentDescription').textContent,/undisturbed/);assert.equal($('fieldView').value,'temperature');});
await check('Heat and cool gestures send signed thermal impulses',async()=>{for(const [mode,sign] of [['heat',1],['cool',-1]]){$('fieldTool').value=mode;$('fieldTool').onchange();$('field').onpointerdown({pointerId:1,clientX:400,clientY:300});const last=messages.at(-1);assert.equal(last.type,'heat');assert.equal(Math.sign(last.amount),sign);$('field').onpointerup();}});
await check('Real fluid snapshots populate measurements and both probe plots',async()=>{const {Instrument}=await import('../dist/fluid.mjs');const inst=new Instrument();inst.noteOn('inspection',60);for(let i=0;i<10;i++)inst.step();inst.tables();const f=inst.fluid,p=[...inst.pickups.values()][0];lastWorker.onmessage({data:{type:'state',n:f.n,u:f.u,v:f.v,dye:f.dye,temperature:f.temperature,vorticity:f.omega,pressure:f.p,metrics:f.diagnostics(),energy:f.energy(),time:f.time,hz:120,cost:2,loops:[p]}});assert.ok(Number($('energyValue').textContent)>0);assert.match($('probeNote').textContent,/C4/);assert.match($('probeRms').textContent,/e[-+]/);for(const mode of ['vorticity','pressure','temperature','speed','tracers']){$('fieldView').value=mode;$('fieldView').onchange();frameCallback(performance.now());assert.ok($('fieldDescription').textContent.length>20);assert.match($('fieldRange').textContent,/DIMENSIONLESS/);}});
await check('Engine diagnostics and restart keep sound settings',async()=>{const old=$('tempo').value;$('statusBtn').onclick();assert.ok($('diagnosticRows').children.length>10);await $('restartBtn').onclick();await flush();assert.equal($('tempo').value,old);assert.equal($('statusDialog').open,false);assert.match($('audioBtn').textContent,/Enable/);});
await writeFile(new URL('../artifacts/app-smoke.json',import.meta.url),JSON.stringify({version:'1.1.0',method:'Node DOM/audio/worker stand-ins; not a real browser',results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} UI wiring checks passed`);if(results.some(r=>!r.pass))process.exitCode=1;
