import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {InputMixer} from '../dist/input-mixer.mjs';
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.message);}}
test('Guitar records with software monitoring disabled',()=>{const m=new InputMixer(),l=new Float32Array(128),r=new Float32Array(128),g=new Float32Array(128).fill(.25);m.process(l,r,[g]);assert.ok(l.every(x=>x===0));assert.ok(r.every(x=>x===0));assert.ok(m.recordL.every(x=>x===.25));assert.ok(m.recordR.every(x=>x===.25));});
test('Input 2 selection does not accidentally record input 1',()=>{const m=new InputMixer();m.setConfig({channel:'right',recordSource:'guitar'});m.process(new Float32Array(128),new Float32Array(128),[new Float32Array(128).fill(.8),new Float32Array(128).fill(.2)]);assert.ok(m.recordL.every(x=>Math.abs(x-.2)<1e-6));m.process(new Float32Array(128),new Float32Array(128),[new Float32Array(128).fill(.8)]);assert.ok(m.recordL.every(x=>x===0));});
test('Stereo input routing preserves separate channels',()=>{const m=new InputMixer();m.setConfig({channel:'stereo',recordSource:'guitar'});m.process(new Float32Array(128),new Float32Array(128),[new Float32Array(128).fill(.1),new Float32Array(128).fill(.4)]);assert.ok(Math.abs(m.recordL[0]-.1)<1e-6);assert.ok(Math.abs(m.recordR[0]-.4)<1e-6);});
test('Guitar-only and synth-only recordings isolate the requested source',()=>{const m=new InputMixer(),g=new Float32Array(128).fill(.3);m.setConfig({recordSource:'guitar'});m.process(new Float32Array(128).fill(.1),new Float32Array(128).fill(.2),[g]);assert.ok(Math.abs(m.recordL[0]-.3)<1e-6);m.setConfig({recordSource:'synth'});m.process(new Float32Array(128).fill(.1),new Float32Array(128).fill(.2),[g]);assert.ok(Math.abs(m.recordL[0]-.1)<1e-6);assert.ok(Math.abs(m.recordR[0]-.2)<1e-6);});
test('Optional monitoring fades in while bounded stereo mix is captured',()=>{const m=new InputMixer(),g=new Float32Array(128).fill(.8);m.setConfig({monitor:true});let l,r;for(let i=0;i<20;i++){l=new Float32Array(128).fill(.7);r=new Float32Array(128).fill(.7);m.process(l,r,[g]);}assert.ok(l.every(x=>x<=.980001));assert.ok(m.recordL.every(x=>x<=1));assert.ok(l[127]>.9);});
test('Hardware clipping is metered and silent disconnection stays finite',()=>{const m=new InputMixer();m.process(new Float32Array(128),new Float32Array(128),[new Float32Array(128).fill(1)]);assert.equal(m.clipped,true);m.process(new Float32Array(128),new Float32Array(128),[]);assert.equal(m.inputPeak,0);assert.ok(m.recordL.every(Number.isFinite));});
let Processor;const sent=[];globalThis.sampleRate=48000;globalThis.AudioWorkletProcessor=class{constructor(){this.port={postMessage:m=>sent.push(m),onmessage:null};}};globalThis.registerProcessor=(_,p)=>{Processor=p;};await import('../dist/audio-worklet.mjs');
test('Actual worklet captures guitar without sending it to the speakers',()=>{const p=new Processor();p.port.onmessage({data:{type:'inputConfig',config:{recordSource:'guitar',monitor:false}}});p.port.onmessage({data:{type:'record'}});const out=[[new Float32Array(128),new Float32Array(128)]];p.process([[new Float32Array(128).fill(.2)]],out);assert.ok(out[0][0].every(x=>x===0));p.port.onmessage({data:{type:'stopRecord'}});const chunk=sent.find(m=>m.type==='recordChunk');assert.equal(chunk.samples.length,256);assert.ok(chunk.samples.every(x=>Math.abs(x-.2)<1e-6));});
await writeFile(new URL('../artifacts/input-tests.json',import.meta.url),JSON.stringify({version:'1.0.0',method:'Synthetic input blocks, no physical hardware',results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} input checks passed`);if(results.some(r=>!r.pass))process.exitCode=1;
