// Independent analytic checks for the fluid model and its sonification.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {Fluid,Pickup,Instrument} from '../dist/fluid.mjs';
import {VERSION,DEFAULTS,createPatch,parsePatch} from '../dist/config.mjs';
const results=[];
function check(name,fn){try{const details=fn();results.push({name,pass:true,...details});console.log('PASS',name,JSON.stringify(details||{}));}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);}}
const rms=a=>Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length),mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
check('Discrete vortex impulse has negligible divergence and net vorticity',()=>{const f=new Fluid();f.vortex(.48,.52,1.2);const d=f.divergence();f.updateVorticity();assert.ok(d<2e-6);assert.ok(Math.abs(mean(f.omega))<1e-7);return {divergenceRms:d};});
check('Pressure projection removes a periodic gradient to solver tolerance',()=>{const f=new Fluid(),n=f.n;for(let j=0;j<n;j++)for(let i=0;i<n;i++){f.u[i+j*n]=Math.sin(2*Math.PI*i/n);f.v[i+j*n]=.6*Math.sin(4*Math.PI*j/n);}const before=f.divergence();f.project(1/120);const after=f.divergence();assert.ok(after/before<2e-6);assert.ok(f.energy()<1e-12);assert.ok(Math.abs(mean(f.p))<1e-10);return {relativeDivergence:after/before,remainingEnergy:f.energy()};});
check('Sinusoidal shear decays at the discrete viscous rate plus exact drag',()=>{
  const errors=[];for(const mode of [1,6]){const f=new Fluid(),n=f.n,dt=1/120,steps=120;f.params.viscosity=.0013;f.params.buoyancy=0;const initial=new Float64Array(f.size);for(let j=0;j<n;j++)for(let i=0;i<n;i++)initial[i+j*n]=f.u[i+j*n]=.3*Math.sin(2*Math.PI*mode*(j+.5)/n);
    const attenuation=(1-4*f.params.viscosity*dt*n*n*Math.sin(Math.PI*mode/n)**2)**steps*Math.exp(-steps*dt/f.params.memory);for(let i=0;i<steps;i++)f.step(dt);const error=rms(f.u.map((x,k)=>x-initial[k]*attenuation))/rms(initial);assert.ok(error<2e-6);errors.push({mode,attenuation,error});}assert.ok(errors[1].attenuation<errors[0].attenuation*.3);return {modes:errors};
});
check('Thermal Fourier mode follows diffusion and cooling without creating motion at B=0',()=>{const f=new Fluid(),n=f.n,steps=120,dt=1/120,mode=3;f.params.buoyancy=0;f.params.diffusivity=.001;const initial=new Float64Array(f.size);for(let j=0;j<n;j++)for(let i=0;i<n;i++)initial[i+j*n]=f.temperature[i+j*n]=.5*Math.cos(2*Math.PI*mode*(i+.5)/n);const factor=(1-4*f.params.diffusivity*dt*n*n*Math.sin(Math.PI*mode/n)**2)**steps*Math.exp(-steps*dt/8);for(let i=0;i<steps;i++)f.step(dt);const error=rms(f.temperature.map((x,k)=>x-initial[k]*factor));assert.ok(error<2e-6);assert.equal(f.energy(),0);return {rmsError:error,attenuation:factor};});
check('Uniform temperature has no buoyant acceleration in the mean-relative model',()=>{const f=new Fluid();f.params.buoyancy=2;f.temperature.fill(1);for(let k=0;k<30;k++)f.step();assert.equal(f.energy(),0);assert.ok(Math.abs(f.temperature[0]-Math.exp(-.25/8))<1e-6);});
check('Hot and cold impulses produce upward and downward local flow',()=>{const a=new Fluid(),b=new Fluid();for(const f of [a,b])f.params.buoyancy=1.5;a.heat(.5,.6,1);b.heat(.5,.6,-1);for(let k=0;k<60;k++){a.step();b.step();}const hot=a.velocity(.5,.6)[1],cold=b.velocity(.5,.6)[1];assert.ok(hot<-.02);assert.ok(cold>.02);assert.ok(Math.abs(mean(a.v))<1e-5&&Math.abs(mean(b.v))<1e-5);return {warmVerticalVelocity:hot,coolVerticalVelocity:cold};});
check('Taylor–Green vortex approaches analytic viscous decay with grid refinement',()=>{
  const errors=[];for(const n of [24,48]){const f=new Fluid(n);f.params.viscosity=.001;f.params.buoyancy=0;f.params.memory=16;const initialU=new Float64Array(f.size),initialV=new Float64Array(f.size),dt=1/120,steps=60;
    for(let j=0;j<n;j++)for(let i=0;i<n;i++){const k=i+j*n;initialU[k]=f.u[k]=.12*Math.sin(2*Math.PI*i/n)*Math.cos(2*Math.PI*(j+.5)/n);initialV[k]=f.v[k]=-.12*Math.cos(2*Math.PI*(i+.5)/n)*Math.sin(2*Math.PI*j/n);}
    const factor=Math.exp(-(8*Math.PI*Math.PI*f.params.viscosity+1/f.params.memory)*steps*dt);for(let k=0;k<steps;k++)f.step(dt);const error=Math.hypot(rms(f.u.map((x,k)=>x-initialU[k]*factor)),rms(f.v.map((x,k)=>x-initialV[k]*factor)))/Math.hypot(rms(initialU),rms(initialV));errors.push(error);
  }assert.ok(errors[1]<.05);assert.ok(errors[1]<errors[0]*.75);return {relativeError24:errors[0],relativeError48:errors[1]};
});
check('Curl and loop circulation agree with solid-body rotation',()=>{const f=new Fluid(),p=new Pickup('rotation',60),n=f.n,spin=.7;for(let j=0;j<n;j++)for(let i=0;i<n;i++){f.u[i+j*n]=-spin*((j+.5)/n-p.cy);f.v[i+j*n]=spin*((i+.5)/n-p.cx);}f.updateVorticity();assert.ok(Math.abs(f.sample(f.omega,p.cx,p.cy,0,0)-2*spin)<1e-5);p.spectrum(f);const expected=2*spin*Math.PI*.095*.075;assert.ok(Math.abs(p.circulation/expected-1)<.004);return {circulation:p.circulation,analytic:expected};});
check('Fixed probes stay put; moving probes follow transport',()=>{const f=new Fluid();f.u.fill(.2);f.v.fill(-.1);const fixed=new Pickup('fixed',60),moving=new Pickup('moving',60),x=fixed.x.slice();f.params.probeMotion=0;fixed.step(f,.04);assert.deepEqual(fixed.x,x);f.params.probeMotion=1;moving.step(f,.04);assert.ok(Math.abs(moving.x[0]-x[0]-.008)<1e-6);});
check('Listen-only notes leave the existing flow and temperature undisturbed',()=>{const inst=new Instrument();inst.fluid.experiment('plume');inst.setParams({excite:0});const u=inst.fluid.u.slice(),t=inst.fluid.temperature.slice();inst.noteOn('observer',60);assert.deepEqual(inst.fluid.u,u);assert.deepEqual(inst.fluid.temperature,t);inst.setParams({excite:1});inst.noteOn('exciter',62);assert.ok(inst.fluid.energy()>0);assert.notDeepEqual(inst.fluid.temperature,t);});
check('All three measured probe signals produce distinct finite DC-free voices',()=>{const a=new Instrument();a.setParams({flow:1,heat:.8});const p=a.noteOn('voice',64);for(let k=0;k<40;k++)a.step();const tables=[];for(const pickup of [0,1,2]){a.setParams({pickup});p.level=0;const table=p.table(a.fluid);assert.ok(table.every(Number.isFinite));assert.ok(Math.abs(mean(table))<1e-6);assert.ok(rms(table)>.005);assert.ok(p.harmonics.some(x=>x>0));tables.push(table);}const changes=[rms(tables[0].map((x,k)=>x-tables[1][k])),rms(tables[0].map((x,k)=>x-tables[2][k]))];assert.ok(changes.every(x=>x>.01));return {waveformDifferences:changes};});
check('Measured pressure is invariant to a constant pressure gauge offset',()=>{const f=new Fluid(),p=new Pickup('gauge',60);f.vortex(.42,.52,1);f.step();f.params.pickup=2;p.level=0;const first=p.table(f);for(let k=0;k<f.size;k++)f.p[k]+=12;p.level=0;const second=p.table(f);assert.ok(rms(first.map((x,k)=>x-second[k]))<1e-4);});
check('Live dimensionless diagnostics obey their definitions',()=>{const f=new Fluid();f.u.fill(.3);f.v.fill(-.4);const d=f.diagnostics();assert.ok(Math.abs(d.energy-.125)<1e-7);assert.ok(Math.abs(d.rmsSpeed-.5)<1e-7);assert.ok(Math.abs(d.reynolds-.5/f.params.viscosity)<.001);assert.ok(Math.abs(d.cfl-.7/120*48)<1e-7);assert.equal(d.enstrophy,0);assert.equal(d.divergence,0);});
check('Thermal stress remains finite without silently clipping velocity',()=>{const f=new Fluid();f.params.buoyancy=2;f.params.diffusivity=.003;f.params.viscosity=.003;for(let k=0;k<240;k++){if(k%20===0){f.heat(.4,.7,1.5);f.heat(.6,.3,-1.5);}f.step();}for(const array of [f.u,f.v,f.temperature,f.p])assert.ok(array.every(Number.isFinite));assert.ok(f.divergence()<1e-4);return {energy:f.energy(),divergence:f.divergence()};});
check('Legacy patches migrate without adding heat or changing probe mode',()=>{const patch=createPatch('Legacy',DEFAULTS);for(const key of ['buoyancy','heat','diffusivity','pickup','probeMotion','excite'])delete patch.params[key];const migrated=parsePatch(patch);assert.equal(migrated.params.buoyancy,0);assert.equal(migrated.params.heat,0);assert.equal(migrated.params.pickup,0);assert.equal(migrated.params.probeMotion,1);const bad=createPatch('Bad mode',DEFAULTS);bad.params.pickup=.5;assert.throws(()=>parsePatch(bad));});
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/physics-tests.json',JSON.stringify({version:VERSION,date:new Date().toISOString(),results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} physics checks passed`);if(results.some(r=>!r.pass))process.exitCode=1;
