import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {writeFile,mkdir} from 'node:fs/promises';
import {Fluid,Pickup,Instrument,TABLE_SIZE} from '../dist/fluid.mjs';
import {AudioEngine} from '../dist/dsp.mjs';
const results=[];
function check(name,fn){const start=performance.now();try{const details=fn();results.push({name,pass:true,ms:+(performance.now()-start).toFixed(1),...details});console.log('PASS',name,JSON.stringify(details||{}));}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.message);}}
const rms=a=>Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length);
const max=a=>Math.max(...a.map(Math.abs));
check('Rest remains at rest',()=>{const f=new Fluid();for(let i=0;i<30;i++)f.step();assert.equal(f.energy(),0);assert.equal(f.divergence(),0);});
check('Uniform periodic flow is preserved with expected drag',()=>{const f=new Fluid();f.u.fill(.3);f.v.fill(-.1);for(let i=0;i<120;i++)f.step();const expected=.3*Math.exp(-1/f.params.memory);assert.ok(Math.abs(f.u[0]-expected)<1e-5);assert.ok(f.divergence()<1e-5);return {relativeError:Math.abs(f.u[0]-expected)/expected};});
check('Projection reduces divergence and kinetic energy',()=>{const f=new Fluid();f.brush(.43,.57,.6,-.3);const before=f.divergence(),e=f.energy();f.project(1/120);const after=f.divergence();assert.ok(after/before<.5);assert.ok(f.energy()<=e*1.001);return {divergenceBefore:before,divergenceAfter:after,ratio:after/before};});
check('Lagrangian loop follows a uniform field',()=>{const f=new Fluid();f.u.fill(.2);f.v.fill(-.1);const p=new Pickup('x',60);const x=p.x[0],y=p.y[0];p.step(f,.01);assert.ok(Math.abs(p.x[0]-x-.002)<1e-6);assert.ok(Math.abs(p.y[0]-y+.001)<1e-6);});
check('Frozen field still retires released pickup loops',()=>{const a=new Instrument();a.setParams({release:.1});a.noteOn('frozen',60);a.frozen=true;a.noteOff('frozen');const e=a.fluid.energy();for(let i=0;i<180;i++)a.step();assert.equal(a.pickups.size,0);assert.equal(a.fluid.energy(),e);});
check('Vortices change the waveform over time',()=>{const inst=new Instrument();const p=inst.noteOn('a',60);const a=p.table(inst.fluid);for(let i=0;i<90;i++)inst.step();const b=p.table(inst.fluid);const change=rms(a.map((x,k)=>x-b[k]));assert.ok(change>.015);assert.ok(rms(b)>.03);assert.ok(Math.abs(b.reduce((s,x)=>s+x,0)/b.length)<1e-6);assert.ok(max(b)<=1.00001);return {waveformRms:rms(b),changeRms:change};});
check('Prior notes leave a measurable fluid memory',()=>{const a=new Instrument(),b=new Instrument();a.noteOn('prior',48);for(let i=0;i<100;i++)a.step();const p=a.noteOn('new',60),q=b.noteOn('new',60);for(let i=0;i<30;i++){a.step();b.step();}const x=p.table(a.fluid),y=q.table(b.fluid),difference=rms(x.map((z,i)=>z-y[i]));assert.ok(difference>.01);return {waveformDifferenceRms:difference};});
check('Harmonic cutoff respects the selected audio bandwidth',()=>{const f=new Fluid(),p=new Pickup('a',96);p.excite(f);f.step();const table=p.table(f,5);let outOfBand=0,inBand=0;for(let h=1;h<=40;h++){let c=0,s=0;for(let i=0;i<TABLE_SIZE;i++){c+=table[i]*Math.cos(2*Math.PI*h*i/TABLE_SIZE);s+=table[i]*Math.sin(2*Math.PI*h*i/TABLE_SIZE);}const energy=c*c+s*s;if(h>5)outOfBand+=energy;else inBand+=energy;}assert.ok(outOfBand/Math.max(inBand,1e-20)<1e-9);return {outOfBandEnergyRatio:outOfBand/inBand};});
check('High-force, high-viscosity stress remains finite',()=>{const a=new Instrument();a.setParams({viscosity:.003,force:1.6,memory:16,brightness:1,flow:1});for(let i=0;i<8;i++)a.noteOn('s'+i,48+i*3);let maxEnergy=0;for(let i=0;i<300;i++){if(i%45===0)a.fluid.brush(.2+(i%5)*.13,.45,.6,-.6);a.step();maxEnergy=Math.max(maxEnergy,a.fluid.energy());}for(const arr of [a.fluid.u,a.fluid.v,a.fluid.p])assert.ok(arr.every(Number.isFinite));assert.ok(maxEnergy<4);for(const t of a.tables())assert.ok(t.table.every(Number.isFinite));return {maxEnergy,finalDivergence:a.fluid.divergence()};});
check('Numerical dissipation at rest after excitation',()=>{const f=new Fluid();f.vortex(.5,.5,.8);const initial=f.energy();for(let i=0;i<240;i++)f.step();assert.ok(f.energy()<initial);return {initialEnergy:initial,finalEnergy:f.energy()};});
check('Audio is silent before notes and pitched at A4',()=>{const a=new AudioEngine(),l=new Float32Array(128),r=new Float32Array(128);a.render(l,r);assert.equal(max(l),0);a.noteOn('a',69,1);const sine=Float32Array.from({length:1024},(_,i)=>Math.sin(i*2*Math.PI/1024));a.updateTable('a',sine);let samples=[];for(let i=0;i<375;i++){a.render(l,r);samples.push(...l);}const tail=samples.slice(24000);let crossings=0;for(let i=1;i<tail.length;i++)if(tail[i-1]<=0&&tail[i]>0)crossings++;const hz=crossings*48000/tail.length;assert.ok(Math.abs(hz-440)<3);assert.ok(rms(tail)>.04);return {measuredHz:hz,rms:rms(tail),peak:max(tail)};});
check('Changing wavetables does not reset oscillator phase',()=>{const a=new AudioEngine(),l=new Float32Array(128),r=new Float32Array(128);a.noteOn('a',69);a.render(l,r);const phase=a.voices.get('a').phase;a.updateTable('a',Float32Array.from({length:1024},(_,i)=>Math.sin(2*Math.PI*i/1024)+.2*Math.sin(6*Math.PI*i/1024)));assert.equal(a.voices.get('a').phase,phase);});
check('Polyphony, clipping guard and note release',()=>{const a=new AudioEngine(),l=new Float32Array(128),r=new Float32Array(128);a.setParams({attack:.005,release:.1,volume:1,echo:0,space:0});const table=Float32Array.from({length:1024},(_,i)=>Math.sin(i*2*Math.PI/1024));for(let i=0;i<8;i++){a.noteOn('p'+i,60+i,1);a.updateTable('p'+i,table);}let peak=0,jump=0,prev=0;for(let i=0;i<120;i++){a.render(l,r);for(const s of l){peak=Math.max(peak,Math.abs(s));jump=Math.max(jump,Math.abs(s-prev));prev=s;}}assert.ok(peak<1&&peak>.05);a.allOff();for(let i=0;i<600;i++)a.render(l,r);assert.equal(a.voices.size,0);assert.ok(max(l)<1e-5);return {peak,maxAdjacentJump:jump};});
check('Eight voices are retained after voice stealing fades',()=>{const a=new AudioEngine(),l=new Float32Array(128),r=new Float32Array(128);for(let i=0;i<16;i++){a.noteOn('n'+i,50+i);for(let j=0;j<20;j++)a.render(l,r);}for(let i=0;i<80;i++)a.render(l,r);assert.ok(a.voices.size<=8);return {voices:a.voices.size};});
check('Engine throughput at target simulation rate',()=>{const a=new Instrument();for(let i=0;i<8;i++)a.noteOn('n'+i,48+i*2);const start=performance.now();for(let i=0;i<180;i++){a.step();if(i%4===0)a.tables();}const ms=performance.now()-start;assert.ok(Number.isFinite(ms));return {wallMilliseconds:+ms.toFixed(1),simulatedMilliseconds:1500,realtimeFactor:+(1500/ms).toFixed(2),environment:'execution container; browser performance not measured'};});
// Exercise the actual worklet message protocol using the Web Audio globals it needs.
let Processor;const sent=[];globalThis.sampleRate=48000;globalThis.AudioWorkletProcessor=class{constructor(){this.port={postMessage:m=>sent.push(m),onmessage:null};}};globalThis.registerProcessor=(name,klass)=>{Processor=klass;};
await import('../dist/audio-worklet.mjs');
check('AudioWorklet records complete stereo frames and finalizes',()=>{const p=new Processor();p.port.onmessage({data:{type:'noteOn',id:'a',note:60,velocity:1}});p.port.onmessage({data:{type:'record'}});const out=[[new Float32Array(128),new Float32Array(128)]];for(let i=0;i<80;i++)p.process([],out);p.port.onmessage({data:{type:'stopRecord'}});const chunks=sent.filter(m=>m.type==='recordChunk');assert.equal(chunks.reduce((s,c)=>s+c.samples.length,0),80*128*2);assert.ok(sent.some(m=>m.type==='recordEnd'));assert.ok(chunks.every(c=>c.samples.every(Number.isFinite)));return {recordedStereoFrames:80*128};});
check('Recording auto-stops at the two-minute limit',()=>{const p=new Processor();p.port.onmessage({data:{type:'record'}});p.recordFrames=48000*120-128;p.process([],[[new Float32Array(128),new Float32Array(128)]]);assert.equal(p.recording,false);assert.ok(sent.some(m=>m.type==='recordEnd'&&m.auto));});
// Test the worker transport with a controlled timer rather than an actual browser.
const workerMessages=[];let tick;const originalInterval=globalThis.setInterval;const originalPerformance=globalThis.performance;let clockMs=0;globalThis.performance={now:()=>clockMs};
globalThis.self={postMessage:m=>workerMessages.push(m),onmessage:null};globalThis.setInterval=fn=>{tick=fn;return 1;};
await import('../dist/simulation-worker.mjs');globalThis.setInterval=originalInterval;
check('Simulation worker supplies sound tables and a matching field snapshot',()=>{self.onmessage({data:{type:'noteOn',id:'integration',note:60,velocity:.8}});clockMs=17;tick();clockMs=34;tick();const tables=workerMessages.find(m=>m.type==='tables'),state=workerMessages.find(m=>m.type==='state');assert.equal(tables.tables[0].id,'integration');assert.equal(tables.tables[0].table.length,1024);assert.equal(state.loops[0].id,'integration');assert.equal(state.u.length,48*48);assert.ok(state.energy>0);});
globalThis.performance=originalPerformance;
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/test-results.json',JSON.stringify({date:new Date().toISOString(),results},null,2));
console.log(`${results.filter(r=>r.pass).length}/${results.length} passed`);if(results.some(r=>!r.pass))process.exitCode=1;
